config/routes.rb
Rails.application.routes.draw do
  get 'student_new/new'

  get 'mypage/info'

  get 'grade/inquiry'

  get 'top/test'
  get 'mypage/mypage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ログイン
  get 'top/index'
  get 'top/adminindex'

  get 'login_test/index'
  post 'login_test/index' # アカウント作成(学生)

  get 'login_test/teachers_new'
  post 'login_test/teachers_new' # アカウント作成(教師)


  get 'login_test/create'
  post 'login_test/create'

  get 'login_test/create_teachers'
  post 'login_test/create_teachers'

  post 'login_test/auth'

  get 'login/index'
  get 'login/teacher'


  get 'login/auth'
  post 'login/auth'

  get 'login/logout'
  post 'login/logout'

  get 'login/id'
  post 'login/id'

  get 'student/list'
  get 'student/password'

  get 'student/edit/:id', to: 'student#edit'
  patch 'student/edit/:id', to: 'student#update'

  get 'student/timetable'

  get 'student/info'

  # get 'student/register'

  # get 'student/password'

  # get 'student/stu_info'

  # get 'student/stu_password'

  # post 'student/password_comp'

  # post 'student/login_check'

  get 'grade/inquiry'

  get 'mypage/top'

  get 'password/edit'

  get 'password/comp'


  get'grade/datacreate'
  post'grade/datacreate'
  get 'grade/create'
  post 'grade/create'

  get 'student_new/new'
  post 'student_new/create'

  get 'studentmanagement/index'
  get 'studentmanagement/new'
  get 'studentmanagement/result'
  get 'studentmanagement/search'

  get 'studentmanagement/news'

  post 'studentmanagement/create'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grade.rb
class Grade < ApplicationRecord
    belongs_to :student
    belongs_to :subject
    
end

app/models/student.rb
class Student < ApplicationRecord
    has_secure_password
    
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :grade 
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :check_logined
  private 
      def check_logined 
          if session[:usr] then
              begin 
                  @usr = Student.find(session[:usr])
              rescue ActiveRecord::Record::RecordnotFound
                  reset_seession
              end 
            elsif session[:admin] then
                begin 
                    @usr = Teacher.find(session[:admin])
                rescue ActiveRecord::Record::RecordnotFound
                    reset_seession
                end 
            end
  

          unless @usr 
              redirect_to controller: :login,  action: :index
          end 
      end

end

app/controllers/grade_controller.rb
class GradeController < ApplicationController
  def inquiry
    nukidasi=Grade.where(student_id:session[:usr])
    @keka = nukidasi.joins(:student,:subject).select("subjects.subject_name,grades.grade")
        
  end
  def datacreate
    @tests=Grade.new
  end 
  def create 
    @grade=Grade.create(person)
    if @grade.save 
      redirect_to 'https://www.google.co.jp/'
    else 
      redirect_to 'https://www.yahoo.co.jp/'
    end
      

  end

  private 
  def person
      params.require(:grade).permit(:students_id,:subjects_id, :grade)
  end 

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    skip_before_action :check_logined
    def index
        render :layout =>'layouts/login'
    end
    def teacher
        render :layout => 'layouts/login'        
    end
    def auth
        usr=Student.find_by(id: params[:studentid])
        admin=Teacher.find_by(id: params[:id])

        if usr && usr.authenticate(params[:password]) then
            session[:usr] = usr.id
            redirect_to controller: :top,  action: :index

        else
            if admin && admin.authenticate(params[:password]) then
                session[:admin] = admin.id
                redirect_to controller: :top,  action: :adminindex
            else
                @error="ユーザー名/パスワードが違う"
                redirect_to controller: :login,  action: :index ,eroor: @error
            end

        end
    end

    def logout
        reset_session
        redirect_to controller: :login,  action: :index
    end

end

app/controllers/login_test_controller.rb
class LoginTestController < ApplicationController
    skip_before_action :check_logined
    def index
        @student = Student.new
    end
    def teachers_new
        @teacher = Teacher.new        
    end 
    def create 
        Student.create(person_params)
    end
    def create_teachers
        Teacher.create(teachers_params)
    end 

    private 
    def person_params
        params.require(:student).permit(:id,:password, :password_confirmation,:k_class,:number,:name)
    end 
    private 
    def teachers_params
        params.require(:teacher).permit(:id,:password, :password_confirmation,:k_class,:name)
    end 

end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def info
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
end

app/controllers/student_controller.rb
class StudentController < ApplicationController

  def list
    @msg = '学生一覧'
    @data = Student.all
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    obj = Student.find(params[:id])
    obj.update(student_params)
    redirect_to '/student/list'
  end

  private
  def student_params
    params.require(:student).permit(:student_no, :password_digest, :k_class, :number, :name)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
        data = Student.find(session[:usr])
        session[:name]=data.name
    end
    def adminindex
        data = Teacher.find(session[:admin] )
        session[:name]=data.name        
        render :layout => 'layouts/admin' 
        
    end 
    def test 
        @id = session[:student_no]
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grade_helper.rb
module GradeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/login_test_helper.rb
module LoginTestHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/studentmanagement_helper.rb
module StudentmanagementHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/login/index.html.erb
<%= form_tag  action: :auth do %>
<center>
        <%= label_tag :studentid, "学生番号" %><br>
        <div class="col-md-2">
        <%= text_field_tag :studentid, '',class:'form-control' %> <br>
        <%= label_tag :password , "パスワード" %><br></div>
        <div class="col-md-2">
        <%= password_field_tag :password, '',class:'form-control' %>
        <br><%= submit_tag 'ログイン', class:'btn btn-primary mb-2' %>
      </div>
<% end %>
<%= link_to "生徒登録画面", :controller => "login_test", :action => "index" %>
<%= link_to "教師登録画面", :controller => "login_test", :action => "teachers_new" %>
<br>
<%= link_to "教師側のログインはこちら", :controller => "login", :action => "teacher" %>
</center>

app/views/login/teacher.html.erb
<%= form_tag  action: :auth do %>
<center>
    <%= label_tag :id, "学教師番号" %><br>
    <div class="col-md-2">
    <%= text_field_tag :id, '',class:'form-control' %> <br>
    <%= label_tag :password , "パスワード" %><br></div>
    <div class="col-md-2">
    <%= password_field_tag :password, '',class:'form-control'%>
    <br><%= submit_tag 'ログイン', class:'btn btn-primary mb-2'%>
  </div>
<% end %>

app/views/login_test/index.html.erb
<%= form_for @student,:url => {:action => :create} do |f| %>
    <div class="field">
      <div class="col-md-2">
        <%= f.label :id, "学生番号" %><br>
        <%= f.text_field :id, class:'form-control' %> <br>
    </div>
  </div>
    <div class="field">
      <div class="col-md-2">
        <%= f.label :password , "パスワード" %><br>
        <%= f.password_field :password ,class:'form-control'%>
    </div>
  </div>
    <div class="field">
      <div class="col-md-2">
        <%= f.label :password_confirmation , "パスワード確認" %><br>
        <%= f.password_field :password_confirmation ,class:'form-control'%>
    </div>
  </div>
    <div class="field">
      <div class="col-md-2">
        <%= f.label :student_no, "クラス" %><br>
        <%= f.text_field :k_class ,class:'form-control'%> <br>
　   </div>
</div>
    <div class="field">
      <div class="col-md-2">
        <%= f.label :number, "番号" %><br>
        <%= f.text_field :number ,class:'form-control'%> <br>
　   </div>
</div>
    <div class="field">
      <div class="col-md-2">
        <%= f.label :number, "名前" %><br>
        <%= f.text_field :name ,class:'form-control'%> <br>
　   </div>
</div>
    <div class="actions" >
      <div class="col-md-3">
        <%= f.submit('登　録' ,class:'btn btn-primary mb-2')%>
    </div>
  </div>
<% end %>

app/views/login_test/teachers_new.html.erb
<%= form_for @teacher,:url => {:action => :create_teachers} do |f| %>
    <div class="field">
      <div class="col-md-2">
        <%= f.label :id, "教師番号" %><br>
        <%= f.text_field :id ,class:"form-control"%> <br>
    </div>
  </div>
    <div class="field">
      <div class="col-md-2">
        <%= f.label :password , "パスワード" %><br>
        <%= f.password_field :password ,class:"form-control"%>
      </div>
    </div>
    <div class="field">
      <div class="col-md-2">
        <%= f.label :password_confirmation , "パスワード確認" %><br>
        <%= f.password_field :password_confirmation ,class:"form-control"%>
      </div>
    </div>
    <div class="field">
      <div class="col-md-2">
        <%= f.label :teacher, "クラス" %><br>
        <%= f.text_field :k_class ,class:"form-control"%> <br>
      </div>
　   </div>
    <div class="field">
      <div class="col-md-2">
        <%= f.label :number, "名前" %><br>
        <%= f.text_field :name ,class:"form-control"%> <br>
　   </div>
</div>
    <div class="actions" >
      <div class="col-md-2">
<%= f.submit('登　録' ,class:'btn btn-primary mb-2')%>
      </div>
    </div>
<% end %>

app/views/mypage/info.html.erb
<%= provide(:title,session[:name]) %>   
<h1>登録情報</h1>

app/views/mypage/mypage.html.erb
<%= provide(:title,session[:name]) %>   
<%= redirect_to controller: :login,  action: :logout  %>

app/views/mypage/top.html.erb
<%= provide(:title,session[:name]) %>   
<%= link_to '登録情報', mypage_info_path %><br>
<%= link_to 'パスワード', password_edit_path %><br>
<%= link_to 'ログアウト' , {controller: :login, action: :logout}  %>

app/views/password/comp.html.erb
<center>
<h1>KCS北九州情報専門学校ポータルサイト</h1>
</center>
<p><center><h2>
<div class="label label-default">パスワード変更完了</div>
</h2></center></p>
<ul><center><h3>
  パスワードを変更しました。</h3></li><br>
</ul></center>

app/views/password/edit.html.erb
<center>
    <h1>KCS北九州情報専門学校</h1>
    <div class="label label-default">
        <h2>パスワード変更</h2>
    </div>
    <p>あなたのパスワードをお好きなパスワードに変更できます。<br>
    セキュリティを高くするために月に1度はパスワードの変更をおすすめします。</p>
    <table>
    <%= form_tag({ controller: :password, action: :comp}, id: :password) do %>
        <tr>
            <th>新しいパスワード</th>
            <td><%= password_field_tag :pass, '', size: 30 %></td>
        </tr>
        <tr>
            <th>新しいパスワード（確認）</th>
            <td><%= password_field_tag :pass, '', size: 30 %></td>
        </tr>
        <tr>
            <td colspan="2"><hr></td>
        </tr>
        <tr>
            <td></td>
            <td><%= submit_tag '変更' %><input type="reset" value="リセット"></td>
        </tr>
    <% end %>
</center>

app/views/top/_id_information.html.erb
<%= provide(:title,session[:name] ) %>

app/views/top/adminindex.html.erb
<h1>Trst</h1>
<%= provide(:title,session[:name]) %>   

app/views/top/index.html.erb
<p><%= link_to '一覧', student_list_path %></p>
<%= provide(:title,session[:name]) %>   
<div id="page-content-wrapper">
    <div class="container">
        <iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=kcskr4%40gmail.com&amp;color=%231B887A&amp;ctz=Asia%2FTokyo" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
        <a target="_blank" href="https://calendar.google.com/calendar/event?action=TEMPLATE&amp;tmeid=NG5xMnBuN2ZqN3RwbGxocDZkOGRnMWs5MGYga2Nza3I0QG0&amp;tmsrc=kcskr4%40gmail.com">
            <img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_ja.gif">
        </a>
    </div>
</div>