config/routes.rb
Rails.application.routes.draw do
  get 'student_new/new'

  get 'mypage/info'

  get 'grade/inquiry'

  get 'top/test'
  get 'mypage/mypage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ログイン
  get 'top/index'
  get 'top/adminindex'

  get 'login_test/index'
  post 'login_test/index' # アカウント作成(学生)

  get 'login_test/teachers_new'
  post 'login_test/teachers_new' # アカウント作成(教師)


  get 'login_test/create'
  post 'login_test/create'

  get 'login_test/create_teachers'
  post 'login_test/create_teachers'

  post 'login_test/auth'

  get 'login/index'
  get 'login/teacher'


  get 'login/auth'
  post 'login/auth'

  get 'login/logout'
  post 'login/logout'

  get 'login/id'
  post 'login/id'

  get 'student/list'
  get 'student/password'

  get 'student/edit/:id', to: 'student#edit'
  patch 'student/edit/:id', to: 'student#update'

  get 'student/timetable'

  get 'student/info'

  # get 'student/register'

  # get 'student/password'

  # get 'student/stu_info'

  # get 'student/stu_password'

  # post 'student/password_comp'

  # post 'student/login_check'

  get 'grade/inquiry'

  get 'mypage/top'

  get 'password/edit'

  get 'password/comp'


  get'grade/datacreate'
  post'grade/datacreate'
  get 'grade/create'
  post 'grade/create'

  get 'student_new/new'
  post 'student_new/create'

  get 'studentmanagement/index'
  get 'studentmanagement/new'
  get 'studentmanagement/result'
  get 'studentmanagement/search'

  get 'studentmanagement/news'

  post 'studentmanagement/create'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grade.rb
class Grade < ApplicationRecord
    belongs_to :student
    belongs_to :subject
    
end

app/models/student.rb
class Student < ApplicationRecord
    has_secure_password
    
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :grade 
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_secure_password
    
end

app/controllers/grade_controller.rb
class GradeController < ApplicationController
  def inquiry
    nukidasi=Grade.where(student_id:session[:usr])
    @keka = nukidasi.joins(:student,:subject).select("subjects.subject_name,grades.grade")
        
  end
  def datacreate
    @tests=Grade.new
  end 
  def create 
    @grade=Grade.create(person)
    if @grade.save 
      redirect_to 'https://www.google.co.jp/'
    else 
      redirect_to 'https://www.yahoo.co.jp/'
    end
      

  end

  private 
  def person
      params.require(:grade).permit(:students_id,:subjects_id, :grade)
  end 

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    skip_before_action :check_logined
    def index
        render :layout =>'layouts/login'
    end
    def teacher
        render :layout => 'layouts/login'        
    end
    def auth
        usr=Student.find_by(id: params[:studentid])
        admin=Teacher.find_by(id: params[:id])

        if usr && usr.authenticate(params[:password]) then
            session[:usr] = usr.id
            redirect_to controller: :top,  action: :index

        else
            if admin && admin.authenticate(params[:password]) then
                session[:admin] = admin.id
                redirect_to controller: :top,  action: :adminindex
            else
                @error="ユーザー名/パスワードが違う"
                redirect_to controller: :login,  action: :index ,eroor: @error
            end

        end
    end

    def logout
        reset_session
        redirect_to controller: :login,  action: :index
    end

end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def info
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
end

app/controllers/student_controller.rb
class StudentController < ApplicationController

  def list
    @msg = '学生一覧'
    @data = Student.all
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    obj = Student.find(params[:id])
    obj.update(student_params)
    redirect_to '/student/list'
  end

  private
  def student_params
    params.require(:student).permit(:student_no, :password_digest, :k_class, :number, :name)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
        data = Student.find(session[:usr])
        session[:name]=data.name
    end
    def adminindex
        data = Teacher.find(session[:admin] )
        session[:name]=data.name        
        render :layout => 'layouts/admin' 
        
    end 
    def test 
        @id = session[:student_no]
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grade_helper.rb
module GradeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/login_test_helper.rb
module LoginTestHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/studentmanagement_helper.rb
module StudentmanagementHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
  <title>Compact - SampleView</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>    
<%= render template:'layouts/admintopsidbar' %>
<%= yield %>


</body>
</html>

app/views/layouts/admintopsidbar.html.erb
<div id="wrapper" class="toggled">
<!-- Sidebar -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand"><%= link_to  yield(:title), mypage_top_path %></li>
        <li><%= link_to '学生管理', studentmanagement_index_path %></li>
        <li><%= link_to '成績登録', student_timetable_path %></li>
        <li><%= link_to "学生連絡登録", student_info_path %></li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Illmatic</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render template:'layouts/topbar' %>
    <%= render template:'layouts/sidebar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Illmatic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/sidebar.html.erb
<div id="wrapper" class="toggled">
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand"><%= link_to  yield(:title), mypage_top_path %></li>
            <li><%= link_to '成績照会', grade_inquiry_path %></li>
            <li><%= link_to '時間割', student_timetable_path %></li>
            <li><%= link_to "学生連絡", student_info_path %></li>
        </ul>
    </div>
    <!-- /#sidebar-wrapper -->
    

app/views/layouts/topbar.html.erb
<nav class="navbar navbar-light" style="background-color: #f0f8ff;">
  <%# <a href="#menu-toggle" class="btn btn-secondary toggled" id="menu-toggle">＝</a> %>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      kcsポータルサイト
    </div>
  </div>
</nav>